#ifndef BUKSANCOMMONLIB_GLOBAL_H
#define BUKSANCOMMONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUKSANCOMMONLIB_LIBRARY)
#define BUKSANCOMMONLIB_EXPORT Q_DECL_EXPORT
#else
#define BUKSANCOMMONLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // BUKSANCOMMONLIB_GLOBAL_H
